# See dunst(5) for all configuration options

[global]
    # The transparency of the window.  Range: [0; 100].
    # This option will only work if a compositing window manager is
    # present (e.g. xcompmgr, compiz, etc.). (X11 only)
    transparency = 50

    # Defines color of the frame around the notification window.
    frame_color = "#aaaaaa"

    # Define a color for the separator.
    # possible values are:
    #  * auto: dunst tries to find a color fitting to the background;
    #  * foreground: use the same color as the foreground;
    #  * frame: use the same color as the frame;
    #  * anything else will be interpreted as a X color.
    separator_color = frame

[urgency_low]
    # IMPORTANT: colors have to be defined in quotation marks.
    # Otherwise the "#" and following would be interpreted as a comment.
    background = "{{colors.surface.default.hex}}"
    foreground = "{{colors.on_surface.default.hex}}"
    frame_color = "{{colors.on_surface.default.hex}}"
    timeout = 10
    # Icon for notifications with low urgency
    ; default_icon = dialog-information

[urgency_normal]
    background = "{{colors.primary_container.default.hex}}"
    foreground = "{{colors.on_primary_container.default.hex}}"
    frame_color = "{{colors.on_primary_container.default.hex}}"
    timeout = 10
    override_pause_level = 30
    # Icon for notifications with normal urgency
    ; default_icon = dialog-information

[urgency_critical]
    background = "{{colors.error_container.default.hex}}"
    foreground = "{{colors.on_error_container.default.hex}}"
    frame_color = "{{colors.error.default.hex}}"
    timeout = 0
    override_pause_level = 60
    # Icon for notifications with critical urgency
    default_icon = dialog-warning
